import { Domain } from "@/types/domain";

// Mock data for development and testing
export const mockDomains: Domain[] = [
  {
    id: "aWNld2FycC5jb20=",
    name: "icewarp.com",
    account_count: 256,
    domain_type: "STANDARD",
    description: "Main production domain for IceWarp services",
    dkim_setup: true,
    groups_with_public_folder: 12,
    groups_with_teamchat: 8,
    groups_with_gal: 5,
    has_certificate: true,
    saas_plan_restricted: false,
  },
  {
    id: "dGVzdC5pY2V3YXJwLmNvbQ==",
    name: "test.icewarp.com",
    account_count: 45,
    domain_type: "PREMIUM",
    description: "Testing environment for development",
    dkim_setup: false,
    groups_with_public_folder: 3,
    groups_with_teamchat: 2,
    groups_with_gal: 1,
    has_certificate: true,
    saas_plan_restricted: true,
  },
  {
    id: "c3RhZ2luZy5pY2V3YXJwLmNvbQ==",
    name: "staging.icewarp.com",
    account_count: 12,
    domain_type: "ENTERPRISE",
    description: "Staging environment for testing new features",
    dkim_setup: true,
    groups_with_public_folder: 1,
    groups_with_teamchat: 1,
    groups_with_gal: 0,
    has_certificate: true,
    saas_plan_restricted: false,
  },
  {
    id: "YXBpLmljZXdhcnAuY29t",
    name: "api.icewarp.com",
    account_count: 89,
    domain_type: "PREMIUM",
    description: "API endpoint domain for integrations",
    dkim_setup: true,
    groups_with_public_folder: 0,
    groups_with_teamchat: 0,
    groups_with_gal: 0,
    has_certificate: true,
    saas_plan_restricted: false,
  },
  {
    id: "bGVnYWN5LmljZXdhcnAuY29t",
    name: "legacy.icewarp.com",
    account_count: 23,
    domain_type: "STANDARD",
    description: "Legacy domain - scheduled for migration",
    dkim_setup: false,
    groups_with_public_folder: 2,
    groups_with_teamchat: 1,
    groups_with_gal: 1,
    has_certificate: false,
    saas_plan_restricted: true,
  },
];

export const mockDomainsResponse = {
  page: 1,
  limit: 10,
  total_count: mockDomains.length,
  items: mockDomains,
};
